### ISSUE TITLE
Screen rotation makes the galleryIndex change

### ISSUE THREAD

**Issue by vilanovi** [robotmedia/RMGallery#1]
Hello Robotmedia,

When rotating the device, the RMGalleryViewController is rotated and the RMGalleryView is layouted. However, in the layout process the gallery index changes (probably because the content offset changes).

Should the expected behaviour be that the gallery index doesn't change even if the RMGalleryView bounds changes (for example, by rotating the screen)? am I correct?

Thanks,
Joan

**Comment by hpique** [comment]
That's correct. Want to fix it? :)
