### ISSUE TITLE
Disadvantages of UIPageViewController?

### ISSUE THREAD

**Issue by marcboquet** [robotmedia/RMGallery#3]
Nice one, thanks!
I was wondering what would prevent to use UIPageViewController to manage the gallery? It would handle the paging "natively" and allow to remove quite a bit of code.
But maybe some of your requirements would make it incompatible?

**Comment by hpique** [comment]
Heya @apalancat! You're welcome. 

I decided against `UIPageViewController` for various reasons. Off the top of my head:
- I wanted to offer standalone components (cell and view) as well as a view controller. E.g., `RMGalleryView` works great when you don't need a full-screen gallery. Using `UIPageViewController` would have made that weird. 
- `UIPageViewController` offers very little customization options. Potentially, RMGallery could support grid layouts and animate between layout changes. And while `UIPageViewController` gives you paging  for free, you get it in a very restrictive way: you have to define the layout at init time and can't change it later.
- You can't reliably predict when the before/after methods of `UIPageViewControllerDataSource` will be called, and this would have complicated things for an index-based data source like `RMGalleryDataSource`.
- Last but not least, `UIPageViewController` is the spawn of Satan and I didn't want that thing anywhere near my code. :)

**Comment by marcboquet** [comment]
Awesome response, I didn't know your feelings about UIPageViewController :smile: 
Thanks @hpique!
